### ISSUE TITLE
Allocator System Design

### ISSUE THREAD

**Issue by Lord-Bach** [filecoin-project/filecoin-plus-roadmap#3]
ETA: 2023-12-31

```[tasklist]
### Tasks
- [ ] https://github.com/filecoin-project/filecoin-plus-roadmap/issues/4
- [ ] https://github.com/filecoin-project/filecoin-plus-roadmap/issues/5
- [ ] https://github.com/filecoin-project/filecoin-plus-roadmap/issues/6
- [ ] https://github.com/filecoin-project/filecoin-plus-roadmap/issues/7
- [ ] https://github.com/filecoin-project/filecoin-plus-roadmap/issues/8
- [ ] https://github.com/filecoin-project/filecoin-plus-roadmap/issues/12
- [ ] https://github.com/filecoin-project/filecoin-plus-roadmap/issues/11
- [ ] https://github.com/filecoin-project/filecoin-plus-roadmap/issues/10
- [ ] https://github.com/filecoin-project/filecoin-plus-roadmap/issues/9
- [ ] Allocator System Design Proposal
- [ ] Allocator Application
- [ ] Rubric and Scoring
- [ ] Post Election Rubric
```
